export const GET_RESTAURANTS = "GET_RESTAURANTS";
export const SELECT_RESTAURANT = "SELECT_RESTAURANT";
export const SUBMIT_REVIEW = "SUBMIT_REVIEW";
export const APPLY_PARK_FILTER = "APPLY_PARK_FILTER";
